import React, { useEffect, useState } from "react";
import { Article } from '../types/article';
import { fetchLatestArticles } from '../utils/articles';
import articlesData from '../data/articles.json';
import '../assets/styles/Project.scss';

// Build-time snapshot generated by scripts/fetch-articles.js (prebuild hook).
const initialArticles: Article[] = articlesData.articles;

function formatDate(isoDate: string): string {
    return new Date(isoDate).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
}

function Articles() {
    const [articles, setArticles] = useState<Article[]>(initialArticles);

    // Freshness layer: try to pull the latest feed via rss2json at runtime.
    // On any failure, silently keep the build-time snapshot.
    useEffect(() => {
        let cancelled = false;
        fetchLatestArticles()
            .then((latest) => {
                if (!cancelled && latest.length > 0) {
                    setArticles(latest);
                }
            })
            .catch(() => { /* keep build-time data */ });
        return () => { cancelled = true; };
    }, []);

    return (
    <div className="projects-container" id="articles">
        <h1>Articles</h1>
        {articles.length === 0 && <p>Coming soon...</p>}

        <div className="projects-grid">
            {articles.map((article) => (
                <div className="project" key={article.link}>
                    {article.thumbnail && (
                        <a href={article.link} target="_blank" rel="noreferrer">
                            <img src={article.thumbnail} className="zoom" alt={article.title} width="100%"/>
                        </a>
                    )}
                    <a href={article.link} target="_blank" rel="noreferrer"><h2>{article.title}</h2></a>
                    <p className="article-date">{formatDate(article.pubDate)}</p>
                    <p>{article.snippet}</p>
                </div>
            ))}
        </div>
    </div>
    );
}

export default Articles;
